version: "3"
services:
  telegram_bot:
    build: ./
    image: "node:16"
    # user: "node"
    container_name: telegram_bot
    working_dir: /home/node/app
    restart: always
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "3001:3001"
    command: "node app.js"
    networks:
      - docker-private-network

networks:
  docker-private-network:
    name: docker-private-network
    external: true